print(3 + 4)   
print(3 - 4)   
print(3 * 4)   
print(3 / 4)   
print(3 **4) 
print(3 % 4)   
print(3 // 4)
print("Benjamin")
print("Gonzalez Marin")
print("Mexico")
print("Im enjoying 30 days of python")